name: deploy_frontend
# Deploys when push is made from frontend folder

on:
  push:
    branches: [ main ]
    paths:
    - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push to Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.48.1
        inlineScript: |
          cd frontend
          az storage blob upload-batch --account-name getresumecounter1278fab4 --auth-mode key -d '$web' -s build/

    - name: Purge CDN Endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.48.1
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "kylewaterssrresume" --name "kylewaterssrresume" --resource-group "azureresume-rg"

    - name: Logout of Azure
      run: az logout